---
- hosts: all
  name: Include dynamic variables
  tasks:
    - name: some task
      include_tasks: ../static-assignments/common.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml
